"""
TouchDesigner DAT Execute helper to auto-set GLSL MAT uShDegree from SogPOP Info DAT.

Usage:
1) Create a DAT Execute DAT.
2) Set it to monitor your SogPOP Info DAT table.
3) Paste this file content into the DAT Execute DAT.
4) Edit the two constants below to match your network paths.

Expected Info DAT row keys from SogPOP:
- shDegree
- shTripletCount (optional fallback)
"""

INFO_DAT_PATH = "sogimporter1/info1"
GLSL_MAT_PATH = "geo1/glslmat1"


def _try_float(text, default_value):
    try:
        return float(text)
    except Exception:
        return float(default_value)


def _degree_from_triplets(triplet_count):
    if triplet_count >= 15:
        return 3.0
    if triplet_count >= 8:
        return 2.0
    if triplet_count >= 3:
        return 1.0
    return 0.0


def _read_info_value(table_dat, key):
    if not table_dat:
        return None
    for row in table_dat.rows():
        if len(row) < 2:
            continue
        if str(row[0]) == key:
            return str(row[1])
    return None


def _apply_sh_degree():
    info_dat = op(INFO_DAT_PATH)
    glsl_mat = op(GLSL_MAT_PATH)
    if info_dat is None or glsl_mat is None:
        return

    sh_degree_text = _read_info_value(info_dat, "shDegree")
    sh_triplets_text = _read_info_value(info_dat, "shTripletCount")

    if sh_degree_text is not None:
        degree = _try_float(sh_degree_text, 0.0)
    elif sh_triplets_text is not None:
        degree = _degree_from_triplets(_try_float(sh_triplets_text, 0.0))
    else:
        degree = 0.0

    degree = max(0.0, min(3.0, round(degree)))

    # Uniform page parameter generated by "Load Uniform Names" for uShDegree.
    # Depending on TD version this may be lowercase or preserve case.
    if hasattr(glsl_mat.par, "Ushdegree"):
        glsl_mat.par.Ushdegree = degree
    elif hasattr(glsl_mat.par, "uShDegree"):
        glsl_mat.par.uShDegree = degree


# DAT Execute callbacks

def onTableChange(dat):
    _apply_sh_degree()
    return


def onPulse(par):
    return


def onCook(dat):
    return


def onStart():
    _apply_sh_degree()
    return
